version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/django/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env_dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=base_django
      - POSTGRES_PASSWORD=base_django
      - POSTGRES_DB=base_django

volumes:
  postgres_data:
